#!/bin/sh
#
# Description:
#
# Options:
# \( -type f -name "*.[Pp][Dd][Ff]" -o -name  "*.[Dd][Jj][Vv][Uu]" -o -name  "*.[Cc][Hh][Mm]" \) 
# Copyleft ¿ 2017 Share and enjoy!

for s in `find  . -not -empty  \( -type f -name "*.[Pp][Dd][Ff]" -o -name  "*.[Dd][Jj][Vv][Uu]" -o -name  "*.[Cc][Hh][Mm]" \) -print0 | xargs -0 ls -l | awk '{print $5}' | sort -n | uniq -d `;
do INUMS=`find . -not -empty -size ${s}c \( -type f -name "*.[Pp][Dd][Ff]" -o -name  "*.[Dd][Jj][Vv][Uu]" -o -name  "*.[Cc][Hh][Mm]" \) -print0 | xargs -0 ls -i | awk '{print $1}'` ;
    for i in ${INUMS}
        do echo ${i} | tr "\r\n" " " &&  echo ${s} | tr "\r\n" " " &&  find .  -type f  -size ${s}c  -inum ${i}  -print0 | xargs -0 md5 | awk '{print $NF}'| tr "\r\n" " "  &&  find . -type f -size ${s}c  -inum ${i} ; 
	   done
    done
